export const stockData = [
  {
    company: "Twitter Inc",
    ticker: "TWTR",
    stockPrice: "22.76 USD",
    timeElapsed: "5 sec ago",
  },
  {
    company: "Square Inc",
    ticker: "SQ",
    stockPrice: "45.28 USD",
    timeElapsed: "10 sec ago",
  },
  {
    company: "Shopify Inc",
    ticker: "SHOP",
    stockPrice: "341.79 USD",
    timeElapsed: "3 sec ago",
  },
  {
    company: "Sunrun Inc",
    ticker: "RUN",
    stockPrice: "9.87 USD",
    timeElapsed: "4 sec ago",
  },
  {
    company: "Adobe Inc",
    ticker: "ADBE",
    stockPrice: "300.99 USD",
    timeElapsed: "10 sec ago",
  },
  {
    company: "HubSpot Inc",
    ticker: "HUBS",
    stockPrice: "115.22 USD",
    timeElapsed: "12 sec ago",
  },
];

export const nftData = [
  {
    img: "/nft1.jpg",
    title: "Thug Monkey",
    price: "20 ETH",
    time: "15h:16m:35s",
    creator: "Alexander",
  },
  {
    img: "/nft2.jpg",
    title: "Broken Face",
    price: "20 ETH",
    time: "8h:6m:45s",
    creator: "Wednesday Adams",
  },
  {
    img: "nft3.jpg",
    title: "Leo Messi",
    price: "20 ETH",
    time: "12h:46m:35s",
    creator: "Emily Wills",
  },
  {
    img: "/nft4.jpg",
    title: "Thug Monkey",
    price: "20 ETH",
    time: "15h:16m:35s",
    creator: "Alexander",
  },
  {
    img: "/nft5.jpg",
    title: "Broken Face",
    price: "20 ETH",
    time: "8h:6m:45s",
    creator: "Wednesday Adams",
  },
  {
    img: "nft6.jpg",
    title: "Leo Messi",
    price: "20 ETH",
    time: "12h:46m:35s",
    creator: "Emily Wills",
  },
  {
    img: "https://www.artnews.com/wp-content/uploads/2022/01/unnamed-2.png?w=631",
    title: "Thug Monkey",
    price: "20 ETH",
    time: "15h:16m:35s",
    creator: "Alexander",
  },
  {
    img: "https://cdn.dribbble.com/users/383277/screenshots/18055765/media/e5fc935b60035305099554810357012a.png?compress=1&resize=400x300",
    title: "Broken Face",
    price: "20 ETH",
    time: "8h:6m:45s",
    creator: "Wednesday Adams",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-QM7Xmt30jlWk55p6zmFJ8Yqgik6DtPFmzC53qQQwlprm9PBrO5QHXLuqiB-JHS9Gqyo&usqp=CAU",
    title: "Leo Messi",
    price: "20 ETH",
    time: "12h:46m:35s",
    creator: "Emily Wills",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoCkiV64IL20KsETEriXYGrfRPSboNO8m6Cw&usqp=CAU",
    title: "Thug Monkey",
    price: "20 ETH",
    time: "15h:16m:35s",
    creator: "Alexander",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQM3-VS1WqpHg-AZmy4slD4DwaWqxziER1Fti5TLJG50E_sFfUWTlujkaKDX9C-5eDDGb0&usqp=CAU",
    title: "Broken Face",
    price: "20 ETH",
    time: "8h:6m:45s",
    creator: "Wednesday Adams",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZXzh70hMKC41n-5AnTv2NKjG4iXW61x7eQveOqHyL8NoP3iKas1W7gp8BLX-A4XgSRjw&usqp=CAU",
    title: "Leo Messi",
    price: "20 ETH",
    time: "12h:46m:35s",
    creator: "Emily Wills",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHeWl4_4GXEsjROWl35IHnHVAzRr3aVLGqMA&usqp=CAU",
    title: "Thug Monkey",
    price: "20 ETH",
    time: "15h:16m:35s",
    creator: "Alexander",
  },
  {
    img: "https://images.prestigeonline.com/wp-content/uploads/sites/6/2022/05/30002705/Galans-Hunger-by-Arya-Mularama-900x900.jpg",
    title: "Broken Face",
    price: "20 ETH",
    time: "8h:6m:45s",
    creator: "Wednesday Adams",
  },
  {
    img: "https://www.christies.com/img/SaleImages/NYR-20447-02252021-1.JPG?width=400&quality=70",
    title: "Leo Messi",
    price: "20 ETH",
    time: "12h:46m:35s",
    creator: "Emily Wills",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSwu48RPJV6Y-02h_Xb-WUd1k4_cND8GmofnA&usqp=CAU",
    title: "Thug Monkey",
    price: "20 ETH",
    time: "15h:16m:35s",
    creator: "Alexander",
  },
  {
    img: "https://www.hollywoodreporter.com/wp-content/uploads/2021/10/Mutant-Demon-Ape-Credit-0xb1-copy-H-2021.jpg?w=1296",
    title: "Broken Face",
    price: "20 ETH",
    time: "8h:6m:45s",
    creator: "Wednesday Adams",
  },
  {
    img: "https://imageio.forbes.com/specials-images/imageserve/621e5699a4be707faf89aafa/0x0.jpg?format=jpg&width=1200",
    title: "Leo Messi",
    price: "20 ETH",
    time: "12h:46m:35s",
    creator: "Emily Wills",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNVkwrbvuoLTtjTIJXUM06vFVcDQsde_1Hmg&usqp=CAU",
    title: "Thug Monkey",
    price: "20 ETH",
    time: "15h:16m:35s",
    creator: "Alexander",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjqltVaqs4cz_CdLawxX3S5aZ9XZ4o8g1ED-kj0t_1oJNBqQwDIHVslaPvJf_gm1k6m1E&usqp=CAU",
    title: "Broken Face",
    price: "20 ETH",
    time: "8h:6m:45s",
    creator: "Wednesday Adams",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSIGqP4rX0uPz9pp8QgSYA6jwUpNNljN1W3EBn3Yym3rmN4lUpYzoRZ9cFLXJ5rMFwkvgA&usqp=CAU",
    title: "Leo Messi",
    price: "20 ETH",
    time: "12h:46m:35s",
    creator: "Emily Wills",
  },
  {
    img: "https://cdn.geekwire.com/wp-content/uploads/2022/07/melaniabilustracion-No-Planet-B-square.jpg",
    title: "Thug Monkey",
    price: "20 ETH",
    time: "15h:16m:35s",
    creator: "Alexander",
  },
  {
    img: "https://i0.wp.com/marketsherald.com/wp-content/uploads/2021/12/Crypto-Samurai.jpg?resize=1000%2C999&ssl=1",
    title: "Broken Face",
    price: "20 ETH",
    time: "8h:6m:45s",
    creator: "Wednesday Adams",
  },
  {
    img: "https://nftevening.com/wp-content/uploads/2022/04/Project-PXN-NFT-collection.png.webp",
    title: "Leo Messi",
    price: "20 ETH",
    time: "12h:46m:35s",
    creator: "Emily Wills",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZV3GBBL85zxu3Y-XFXFN2JKOh54OkDsJK4eSA5KduPjMkW9AeVdv7Jm_vnwwqjyK9jiM&usqp=CAU",
    title: "Thug Monkey",
    price: "20 ETH",
    time: "15h:16m:35s",
    creator: "Alexander",
  },
  {
    img: "https://i.redd.it/5iniaiyhg0y41.jpg",
    title: "Broken Face",
    price: "20 ETH",
    time: "8h:6m:45s",
    creator: "Wednesday Adams",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnTtZ5xFLcMmV_ZQOg2UjKaBidsOU1kbVy-A&usqp=CAU",
    title: "Leo Messi",
    price: "20 ETH",
    time: "12h:46m:35s",
    creator: "Emily Wills",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZRbop9bO893eAAIQl8ZzDllmr0EY6S4UYp1MfR_1Ib5G7vBgwWcZGyVTHBTV1ImfHI18&usqp=CAU",
    title: "Thug Monkey",
    price: "20 ETH",
    time: "15h:16m:35s",
    creator: "Alexander",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSH9wmEeCegggZ5DQ5DJa3LjG0wahZ8C8eplFkGvn26dmqEcw1Njx87A4XvtKLZPUcnjRs&usqp=CAU",
    title: "Broken Face",
    price: "20 ETH",
    time: "8h:6m:45s",
    creator: "Wednesday Adams",
  },
  {
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQe32gv7qKqdZ4o1P_6tez23JANqlVBVi8ipA&usqp=CAU",
    title: "Leo Messi",
    price: "20 ETH",
    time: "12h:46m:35s",
    creator: "Emily Wills",
  },
];
